[tool.poetry]
name = "edesdetect"
version = "0.1.0"
description = ""
authors = ["Magnus Dalen Kvalevåg <magnus.kvalevag@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
jaxlib = {url = "https://storage.googleapis.com/jax-releases/cuda111/jaxlib-0.1.71+cuda111-cp38-none-manylinux2010_x86_64.whl"}
jax = "^0.2.20"
SimpleITK = "^2.1.1"
pandas = "^1.3.3"
opencv-python = "^4.5.1"
dm-haiku = "^0.0.4"
coax = "^0.1.6"
optax = "^0.0.9"
gym = "^0.20.0"
torch = "^1.9.0"
toml = "^0.10.2"
chex = "^0.0.8"
scikit-learn = "^0.24.2"
tensorflow = "^2.6.0"
dm-acme = {version = "^0.2.2", extras = ["jax"]}
tensorflow-probability = "^0.13.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
PySimpleGUI = "^4.47.0"
matplotlib = "^3.4.3"
black = "^21.4b2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
