[tool.poetry]
name = "edesdetect"
version = "0.1.0"
description = ""
authors = ["Magnus Dalen Kvalevåg <magnus.kvalevag@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
jaxlib = {url = "https://storage.googleapis.com/jax-releases/cuda111/jaxlib-0.1.71+cuda111-cp38-none-manylinux2010_x86_64.whl"}
jax = "^0.2.20"
SimpleITK = "^2.1.1"
pandas = "^1.3.3"
opencv-python = "^4.5.1"
dm-haiku = "^0.0.4"
optax = "^0.0.9"
gym = "^0.20.0"
torch = "^1.9.0"
toml = "^0.10.2"
chex = "^0.0.8"
scikit-learn = "^0.24.2"
tensorflow = "^2.6.0"
dm-acme = {version = "^0.2.2", extras = ["jax"]}
# There's a requirement for tensorflow >= 2.7.0 (which is unreleased 
# btw) in the newest version of tensorflow-probability (which is the 
# same as tfp-nightly). We have to depend on an earlier version.
tfp-nightly = "^0.14.0.dev20210915"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
PySimpleGUI = "^4.47.0"
matplotlib = "^3.4.3"
black = "^20.8b1"
ipykernel = "^6.4.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
